Verify sign-off email address against committer email field
mgorny/assign-pull-requests pull request #1
Opened 2019-12-27 23:00 UTC by robbat2

Fixes: https://bugs.gentoo.org/show_bug.cgi?id=703684
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

2023-09-30 08:40 UTC, mgorny requested changes
I'm sorry for missing this earlier.

Also, please follow PEP 8 formatting.

2023-09-30 08:40 UTC, mgorny commented on assign-pull-requests.py
> +    signofflines = [x for x in lines if RE_SIGNOFFBY.match(x)]
Regex seems like a major overkill here.

2023-09-30 08:40 UTC, mgorny commented on assign-pull-requests.py
> +        possible_emails = [word for word in re.split(r'\s+', line) if '@' in word]
Do we really want to hack it like this? I'd say using [email.utils.parseaddr](https://docs.python.org/3/library/email.utils.html#email.utils.parseaddr) would be better.

2023-09-30 15:19 UTC, mgorny commented on assign-pull-requests.py
> +    """ Given a commit, it is considered to contain a correct sign-off IFF:
Let's try to at least roughly follow PEP 257.

2023-09-30 15:19 UTC, mgorny commented on assign-pull-requests.py
> +        if line.lower().startswith('signed-off-by:'):
I suppose you could store `line.lower()` in a helper var, and avoid the `.lower()` below too.

2023-09-30 15:19 UTC, mgorny commented on assign-pull-requests.py
> +            _signed_name, signed_email = email.utils.parseaddr(line)
```suggestion
            _, signed_email = email.utils.parseaddr(line)
```

2023-09-30 17:25 UTC, mgorny approved these changes
LGTM (but note that I didn't test it).

2023-11-27 21:42 UTC, robbat2 commented
@mgorny  can you merge please?

2023-11-30 05:40 UTC, closed without merging

2023-11-30 05:40 UTC, mgorny commented
Done, thanks!